project:
  type: website
  output-dir: docs

website:
  title: "Connor Beebe"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - pairsmodel.qmd
      - RBOBproj.qmd
      - assetclasses.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

